name: Deploy React SPA to Contabo

# Run the workflow when pushing to the master branch
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Get the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18   # or any LTS version
          cache: yarn

      #3) npm ci and build
      - name: Install dependencies and build
        run: |
          yarn install --frozen-lockfile
          yarn build       

      # 4) Copy the contents of build/ to server via SSH
      - name: Sync build to Contabo
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: build/                
          remote_path: /var/www/my-social-network
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}

      # 5) (optional) - restart nginx if you made any changes to the config.
      # - name: Reload Nginx
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       sudo systemctl reload nginx
